### ISSUE TITLE
Problems with computing and plotting fixes

### ISSUE THREAD

**Issue by mikeguler** [unitedstatespowersquadrons/celestial-tools#2]
I’ve been reviewing the future Celestial Navigation student manual and checking some of the homework answers.  I’ve been checking my work with Celestial Tools as a student might do.  In that process, I’ve found some issues with Fix computations and plots.

To reproduce the issues, you need the attached sight log file called:  ch10_hw.txt

The first one is a suggested update to a two-body fix when the boat moves between sights, such as an RFix using a morning and an afternoon sun sight.  The problem is documented in the attached Word doc:  rfix_plotting_suggesting.docx.

The second issue is a bug when computing 3 or more body fixes.  This bug is documented in the attached Word doc:  3-body_fix_bug.docx.

[ch10_hw.txt](https://github.com/unitedstatespowersquadrons/celestial-tools/files/4404357/ch10_hw.txt)
[rfix_plotting_suggestion.docx](https://github.com/unitedstatespowersquadrons/celestial-tools/files/4404360/rfix_plotting_suggestion.docx)
[3-body_fix_bug.docx](https://github.com/unitedstatespowersquadrons/celestial-tools/files/4404361/3-body_fix_bug.docx)

**Comment by hhammon0825** [comment]
Both issues have been addressed in the current CT download dated 3/31/2020. 
Fix form now properly calculates all types of fixes. The CLS Plot form and Custom Plot form both 
modified to plot a 2 body sun sight fix to advance the earlier sight to the later .
